name: Deploy API para MonsterASP

on:
  push:
    branches:
      - "master"
      - "homologacao"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4
      
      - name: Configurar .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Restaurar dependências
        run: |
          dotnet restore ShieldJWT/ShieldJWT.csproj
          dotnet restore ShieldJWTLib/ShieldJWTLib.csproj

      - name: Definir ambiente de deploy
        id: define-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "DEPLOY_ENV=Production" >> $GITHUB_ENV
            echo "CONFIGURATION=Release" >> $GITHUB_ENV
            echo "FTP_SERVER=${{ secrets.FTP_SERVER }}" >> $GITHUB_ENV
            echo "FTP_USERNAME=${{ secrets.FTP_USERNAME }}" >> $GITHUB_ENV
            echo "FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=Staging" >> $GITHUB_ENV
            echo "CONFIGURATION=Debug" >> $GITHUB_ENV
            echo "FTP_SERVER=${{ secrets.FTP_SERVER_HOM }}" >> $GITHUB_ENV
            echo "FTP_USERNAME=${{ secrets.FTP_USERNAME_HOM }}" >> $GITHUB_ENV
            echo "FTP_PASSWORD=${{ secrets.FTP_PASSWORD_HOM }}" >> $GITHUB_ENV
          fi
      
      - name: Compilar aplicação
        run: |
          dotnet build ShieldJWT/ShieldJWT.csproj --configuration ${{ env.CONFIGURATION }} --no-restore
          dotnet build ShieldJWTLib/ShieldJWTLib.csproj --configuration ${{ env.CONFIGURATION }} --no-restore
      
      - name: Publicar aplicação
        run: |
            dotnet publish ShieldJWT/ShieldJWT.csproj -c ${{ env.CONFIGURATION }} -o ./publish

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ env.FTP_SERVER }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /wwwroot/
